server:
  port: 8083

spring:
  application:
    name: order
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservices_Orders?createDatabaseIfNotExist=true
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8088
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
